

import type { ConsumableItem } from '@/types/items';
import { GameBalance } from '@/config/game-balance';

export const ALL_CONSUMABLES: ConsumableItem[] = [
  // Healing Consumables
  {
    id: 'potion',
    name: 'Pozione',
    description: 'Recupera una piccola quantità di HP.',
    category: 'Cura',
    iconName: 'FlaskConical',
    effect: { type: 'heal', amount: GameBalance.POTION_HEAL_AMOUNT },
    cost: 10,
  },
  {
    id: 'superpotion',
    name: 'Superpozione',
    description: 'Recupera una media quantità di HP.',
    category: 'Cura',
    iconName: 'Medal', // Differentiated from Potion
    effect: { type: 'heal', amount: GameBalance.SUPERPOTION_HEAL_AMOUNT },
    cost: 25,
  },
  {
    id: 'antidote',
    name: 'Antidoto',
    description: 'Cura lo stato di Veleno e recupera una piccola quantità di HP.',
    category: 'Cura',
    iconName: 'ShieldAlert',
    effect: { type: 'heal', amount: GameBalance.ANTIDOTE_HEAL_AMOUNT, curesStatus: ['poison'] },
    cost: 15,
  },
  {
    id: 'antiscottatura',
    name: 'Antiscottatura',
    description: 'Cura lo stato di Scottatura e recupera una piccola quantità di HP.',
    category: 'Cura',
    iconName: 'ShieldCheck', // Using ShieldCheck as FlameOff not available
    effect: { type: 'heal', amount: GameBalance.ANTISCOTTATURA_HEAL_AMOUNT, curesStatus: ['burn'] },
    cost: 15,
  },
  {
    id: 'curatotale',
    name: 'Cura Totale',
    description: 'Recupera tutti gli HP di una creatura.',
    category: 'Cura',
    iconName: 'HeartPulse',
    effect: { type: 'heal', percentage: GameBalance.CURA_TOTALE_HEAL_PERCENTAGE },
    cost: 50,
  },
  // Stat Booster Consumables (Integratori)
  {
    id: 'proteina',
    name: 'Proteina',
    description: `Aumenta permanentemente la statistica base di Attacco del ${(GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE * 100).toFixed(0)}%.`,
    category: 'Integratore Statistiche',
    iconName: 'Sword',
    effect: { type: 'stat_boost', stat: 'attackStat', percentage: GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE },
    cost: 200,
  },
  {
    id: 'ferro',
    name: 'Ferro',
    description: `Aumenta permanentemente la statistica base di Difesa del ${(GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE * 100).toFixed(0)}%.`,
    category: 'Integratore Statistiche',
    iconName: 'Shield',
    effect: { type: 'stat_boost', stat: 'defenseStat', percentage: GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE },
    cost: 200,
  },
  {
    id: 'calcio',
    name: 'Calcio',
    description: `Aumenta permanentemente la statistica base di Attacco Speciale del ${(GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE * 100).toFixed(0)}%.`,
    category: 'Integratore Statistiche',
    iconName: 'Sparkles',
    effect: { type: 'stat_boost', stat: 'specialAttackStat', percentage: GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE },
    cost: 200,
  },
  {
    id: 'zinco',
    name: 'Zinco',
    description: `Aumenta permanentemente la statistica base di Difesa Speciale del ${(GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE * 100).toFixed(0)}%.`,
    category: 'Integratore Statistiche',
    iconName: 'ShieldCheck',
    effect: { type: 'stat_boost', stat: 'specialDefenseStat', percentage: GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE },
    cost: 200,
  },
  {
    id: 'magnesio',
    name: 'Magnesio',
    description: `Aumenta permanentemente la statistica base di Velocità del ${(GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE * 100).toFixed(0)}%.`,
    category: 'Integratore Statistiche',
    iconName: 'Gauge',
    effect: { type: 'stat_boost', stat: 'speedStat', percentage: GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE },
    cost: 200,
  },
  {
    id: 'carboidrato',
    name: 'Carboidrato',
    description: `Aumenta permanentemente gli HP massimi del ${(GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE * 100).toFixed(0)}%.`,
    category: 'Integratore Statistiche',
    iconName: 'Heart',
    effect: { type: 'stat_boost', stat: 'maxHealth', percentage: GameBalance.STAT_BOOST_CONSUMABLE_PERCENTAGE },
    cost: 200,
  },
  // Special Consumables
  {
    id: 'creatina',
    name: 'Creatina',
    description: `Aumenta il livello corrente della creatura di +${GameBalance.CREATINA_LEVEL_UP_AMOUNT}.`,
    category: 'Speciale',
    iconName: 'Star',
    effect: { type: 'level_up', levels: GameBalance.CREATINA_LEVEL_UP_AMOUNT },
    cost: 500,
  },
  // Capture Tools
  {
    id: 'sbiruball',
    name: 'Sbiruball',
    description: 'Uno strumento sferico usato per catturare le creature selvatiche.',
    category: 'Strumenti di Cattura',
    iconName: 'Circle',
    effect: { type: 'capture', chance: 0.5 },
    cost: 40,
  },
    {
    id: 'super_sbiruball',
    name: 'Super Sbiruball',
    description: 'Una Sbiruball migliorata con una maggiore probabilità di cattura.',
    category: 'Strumenti di Cattura',
    iconName: 'Circle',
    effect: { type: 'capture', chance: 0.7 },
    cost: 100,
  },
  {
    id: 'mega_sbiruball',
    name: 'Mega Sbiruball',
    description: 'La Sbiruball più potente. Non fallisce mai.',
    category: 'Strumenti di Cattura',
    iconName: 'Circle',
    effect: { type: 'capture', chance: 1.0 },
    cost: 500,
  },
  // Remains
  {
    id: 'piuma',
    name: 'Piuma',
    description: 'Una piuma leggera. Se usata dal Maestro Stregone, può innescare un\'evoluzione forzata...',
    category: 'Resti',
    iconName: 'Feather',
    effect: { type: 'evolve_chance', chance: GameBalance.REMAINS_EVOLVE_CHANCE },
    cost: 50,
  },
  {
    id: 'guscio_di_tartaruga',
    name: 'Guscio di Tartaruga',
    description: 'Un frammento di guscio. Se usato dal Maestro Stregone, può innescare un\'evoluzione forzata...',
    category: 'Resti',
    iconName: 'Shield',
    effect: { type: 'evolve_chance', chance: GameBalance.REMAINS_EVOLVE_CHANCE },
    cost: 50,
  },
  {
    id: 'dente',
    name: 'Dente',
    description: 'Un dente affilato. Se usato dal Maestro Stregone, può innescare un\'evoluzione forzata...',
    category: 'Resti',
    iconName: 'Bone',
    effect: { type: 'evolve_chance', chance: GameBalance.REMAINS_EVOLVE_CHANCE },
    cost: 50,
  },
   // Black Market - Steroids
  {
    id: 'steroide_attacco',
    name: 'Steroidi (Attacco)',
    description: 'Aumenta permanentemente la crescita della statistica di Attacco del 15%.',
    category: 'Potenziamenti Illegali',
    iconName: 'Beaker',
    effect: { type: 'growth_boost', stat: 'attackStat', percentage: 0.15 },
    cost: 1000,
  },
  {
    id: 'steroide_difesa',
    name: 'Steroidi (Difesa)',
    description: 'Aumenta permanentemente la crescita della statistica di Difesa del 15%.',
    category: 'Potenziamenti Illegali',
    iconName: 'Beaker',
    effect: { type: 'growth_boost', stat: 'defenseStat', percentage: 0.15 },
    cost: 1000,
  },
  {
    id: 'steroide_att_spec',
    name: 'Steroidi (Att. Sp.)',
    description: 'Aumenta permanentemente la crescita dell\'Attacco Speciale del 15%.',
    category: 'Potenziamenti Illegali',
    iconName: 'Beaker',
    effect: { type: 'growth_boost', stat: 'specialAttackStat', percentage: 0.15 },
    cost: 1000,
  },
  {
    id: 'steroide_dif_spec',
    name: 'Steroidi (Dif. Sp.)',
    description: 'Aumenta permanentemente la crescita della Difesa Speciale del 15%.',
    category: 'Potenziamenti Illegali',
    iconName: 'Beaker',
    effect: { type: 'growth_boost', stat: 'specialDefenseStat', percentage: 0.15 },
    cost: 1000,
  },
  {
    id: 'steroide_velocita',
    name: 'Steroidi (Velocità)',
    description: 'Aumenta permanentemente la crescita della Velocità del 15%.',
    category: 'Potenziamenti Illegali',
    iconName: 'Beaker',
    effect: { type: 'growth_boost', stat: 'speedStat', percentage: 0.15 },
    cost: 1000,
  },
  {
    id: 'steroide_totale',
    name: 'Steroidi (Totale)',
    description: 'Aumenta permanentemente la crescita di TUTTE le statistiche del 15%.',
    category: 'Potenziamenti Illegali',
    iconName: 'Beaker',
    effect: { type: 'growth_boost', stat: 'all', percentage: 0.15 },
    cost: 5000,
  },
];
